[package]
name = "rust_io"
version = "0.6.0"
edition = "2021"
description="Macro implementation for [rust_io] defining several operators to be used emulating Haskel [do notation]"
license="Apache-2.0"

[dependencies]
futures = "0.3"
rand = "0.8.5"
async-std = "1.12.0"