[package]
name = "kds-feature"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config       = "1.2"
aws-sdk-kinesis  = "1.2"
tokio            = { version = "1", features = ["full"] }
anyhow           = "1"

