[package]
name = "rust_chain"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2   = "0.10"        # hashing SHA-256
serde  = { version = "1.0", features = ["derive"] }
serde_json = "1.0"     # para imprimir la cadena
chrono = "0.4"         # marca temporal

