[package]
name = "ai_hello_world_model"
version = "0.1.0"
edition = "2021"

[dependencies]
csv            = "1"
serde          = { version = "1.0", features = ["derive"] }
bincode        = "1.3"
itertools      = "0.12"
ndarray        = "0.15"
linfa          = "0.7.1"
linfa-logistic = "0.7.1"

